version: "3"
services:
  nginx:
    build: ./docker/nginx/
    container_name: 'nginx-container'
    ports:
      - 80:80
      - 443:443
    links:
      - php
    volumes:
      - ./src/:/var/www/html/
    tty: true

  php:
    build: ./docker/php/
    container_name: 'php-container'
    expose:
      - 9000
    volumes:
      - ./src/:/var/www/html/
